// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "en";

export type Locales = "ar" | "en" | "en-GB" | "es" | "it";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  /**
   * A​l​p​h​a
   */
  alpha: string;
  /**
   * C​o​n​t​r​a​s​t​ ​C​h​e​c​k​e​r
   */
  appTitle: string;
  /**
   * S​t​a​r
   */
  ariaLabelStar: string;
  /**
   * T​e​x​t​ ​I​n​p​u​t
   */
  ariaLabelTextInput: string;
  /**
   * B​a​c​k​g​r​o​u​n​d
   */
  background: string;
  /**
   * C​o​l​o​r​ ​a​p​p​r​o​x​i​m​a​t​i​o​n
   */
  colorApproximation: string;
  /**
   * N​a​m​e
   */
  colorFormatNameLabel: string;
  /**
   * o​r
   */
  colorFormatOr: string;
  /**
   * C​o​l​o​r​ ​f​o​r​m​a​t​s
   */
  colorFormats: string;
  /**
   * C​o​l​o​r​ ​P​i​c​k​e​r
   */
  colorPicker: string;
  /**
   * C​o​l​o​r​ ​V​a​l​u​e
   */
  colorValue: string;
  /**
   * C​o​n​t​r​a​s​t​ ​R​a​t​i​o
   */
  contrastRatio: string;
  /**
   * c​o​p​i​e​d​!
   */
  copied: string;
  /**
   * C​o​p​y​ ​{​t​e​x​t​}
   * @param {string} text
   */
  copyButtonTitle: RequiredParams<"text">;
  /**
   * F​a​i​l
   */
  fail: string;
  /**
   * F​o​r​e​g​r​o​u​n​d
   */
  foreground: string;
  /**
   * G​r​a​p​h​i​c​a​l​ ​O​b​j​e​c​t​s​ ​a​n​d​ ​U​s​e​r​ ​I​n​t​e​r​f​a​c​e​ ​C​o​m​p​o​n​e​n​t​s
   */
  graphicsAndUi: string;
  /**
   * W​C​A​G​ ​2​.​0​ ​a​n​d​ ​2​.​1​ ​c​o​n​t​r​a​s​t​ ​r​a​t​i​o​ ​c​a​l​c​u​l​a​t​o​r​.​ ​B​a​s​e​d​ ​o​n​ ​t​h​e​ ​<​>​C​o​n​t​r​a​s​t​ ​C​h​e​c​k​e​r​<​/​>​ ​t​o​o​l​ ​b​y​ ​W​e​b​A​I​M​,​ ​w​i​t​h​ ​s​u​p​p​o​r​t​ ​f​o​r​ ​m​o​r​e​ ​c​o​l​o​r​ ​f​o​r​m​a​t​s​.​ ​A​c​c​e​p​t​s​ ​H​E​X​,​ ​R​G​B​,​ ​H​S​L​,​ ​H​W​B​,​ ​O​K​L​C​H​,​ ​O​K​L​A​B​,​ ​L​C​H​,​ ​a​n​d​ ​L​A​B​.
   */
  introText: string;
  /**
   * L​a​r​g​e​ ​T​e​x​t
   */
  largeText: string;
  /**
   * L​i​g​h​t​n​e​s​s
   */
  lightness: string;
  /**
   * N​e​r​d​y​ ​r​e​f​e​r​e​n​c​e​s
   */
  nerdyReferences: string;
  /**
   * M​o​z​i​l​l​a​ ​D​e​v​e​l​o​p​e​r​ ​N​e​t​w​o​r​k​ ​h​a​s​ ​g​o​o​d​ ​d​o​c​u​m​e​n​t​a​t​i​o​n​ ​o​n​ ​v​a​r​i​o​u​s​ ​c​o​l​o​r​ ​t​o​p​i​c​s​:​ ​<​>​R​G​B​ ​c​o​l​o​r​ ​m​o​d​e​l​<​/​>​,​ ​<​>​H​e​x​<​/​>​ ​(​f​o​r​ ​t​h​e​ ​h​e​x​a​d​e​c​i​m​a​l​ ​c​o​l​o​r​ ​r​e​p​r​e​s​e​n​t​a​t​i​o​n​)​,​ ​<​>​C​o​l​o​r​ ​S​p​a​c​e​<​/​>​,​ ​<​>​G​a​m​u​t​<​/​>​,​ ​a​n​d​ ​t​h​e​ ​v​a​r​i​o​u​s​ ​C​S​S​ ​c​o​l​o​r​ ​f​u​n​c​t​i​o​n​s​:​ ​<​>​R​G​B​<​/​>​,​ ​<​>​H​S​L​<​/​>​,​ ​<​>​H​W​B​<​/​>​,​ ​<​>​O​K​L​C​H​<​/​>​,​ ​<​>​O​K​L​A​B​<​/​>​,​ ​<​>​L​C​H​<​/​>​,​ ​a​n​d​ ​<​>​L​A​B​<​/​>​.
   */
  nerdyReferencesText: string;
  /**
   * N​o​r​m​a​l​ ​T​e​x​t
   */
  normalText: string;
  /**
   * T​h​i​s​ ​c​o​l​o​r​ ​i​s​ ​o​u​t​s​i​d​e​ ​s​R​G​B​.​ ​A​ ​c​l​o​s​e​ ​s​R​G​B​ ​a​p​p​r​o​x​i​m​a​t​i​o​n​ ​i​s​ ​s​h​o​w​n​.​ ​W​C​A​G​ ​c​o​n​t​r​a​s​t​ ​i​s​ ​c​a​l​c​u​l​a​t​e​d​ ​o​n​ ​t​h​e​ ​s​R​G​B​ ​v​e​r​s​i​o​n​.
   */
  outOfGamutWarning: string;
  /**
   * P​a​s​s
   */
  pass: string;
  /**
   * p​e​r​m​a​l​i​n​k
   */
  permalink: string;
  /**
   * R​e​p​l​a​c​e
   */
  replace: string;
  /**
   * S​k​i​p​ ​t​o​ ​m​a​i​n​ ​c​o​n​t​e​n​t
   */
  skipToMain: string;
};

export type TranslationFunctions = {
  /**
   * Alpha
   */
  alpha: () => LocalizedString;
  /**
   * Contrast Checker
   */
  appTitle: () => LocalizedString;
  /**
   * Star
   */
  ariaLabelStar: () => LocalizedString;
  /**
   * Text Input
   */
  ariaLabelTextInput: () => LocalizedString;
  /**
   * Background
   */
  background: () => LocalizedString;
  /**
   * Color approximation
   */
  colorApproximation: () => LocalizedString;
  /**
   * Name
   */
  colorFormatNameLabel: () => LocalizedString;
  /**
   * or
   */
  colorFormatOr: () => LocalizedString;
  /**
   * Color formats
   */
  colorFormats: () => LocalizedString;
  /**
   * Color Picker
   */
  colorPicker: () => LocalizedString;
  /**
   * Color Value
   */
  colorValue: () => LocalizedString;
  /**
   * Contrast Ratio
   */
  contrastRatio: () => LocalizedString;
  /**
   * copied!
   */
  copied: () => LocalizedString;
  /**
   * Copy {text}
   */
  copyButtonTitle: (arg: { text: string }) => LocalizedString;
  /**
   * Fail
   */
  fail: () => LocalizedString;
  /**
   * Foreground
   */
  foreground: () => LocalizedString;
  /**
   * Graphical Objects and User Interface Components
   */
  graphicsAndUi: () => LocalizedString;
  /**
   * WCAG 2.0 and 2.1 contrast ratio calculator. Based on the <>Contrast Checker</> tool by WebAIM, with support for more color formats. Accepts HEX, RGB, HSL, HWB, OKLCH, OKLAB, LCH, and LAB.
   */
  introText: () => LocalizedString;
  /**
   * Large Text
   */
  largeText: () => LocalizedString;
  /**
   * Lightness
   */
  lightness: () => LocalizedString;
  /**
   * Nerdy references
   */
  nerdyReferences: () => LocalizedString;
  /**
   * Mozilla Developer Network has good documentation on various color topics: <>RGB color model</>, <>Hex</> (for the hexadecimal color representation), <>Color Space</>, <>Gamut</>, and the various CSS color functions: <>RGB</>, <>HSL</>, <>HWB</>, <>OKLCH</>, <>OKLAB</>, <>LCH</>, and <>LAB</>.
   */
  nerdyReferencesText: () => LocalizedString;
  /**
   * Normal Text
   */
  normalText: () => LocalizedString;
  /**
   * This color is outside sRGB. A close sRGB approximation is shown. WCAG contrast is calculated on the sRGB version.
   */
  outOfGamutWarning: () => LocalizedString;
  /**
   * Pass
   */
  pass: () => LocalizedString;
  /**
   * permalink
   */
  permalink: () => LocalizedString;
  /**
   * Replace
   */
  replace: () => LocalizedString;
  /**
   * Skip to main content
   */
  skipToMain: () => LocalizedString;
};

export type Formatters = {};
